version: '3.8'
services:
  exporter:
    image: quay.io/prometheus/node-exporter:latest
    container_name: exporter
    restart: always
    network_mode: host
    pid: host
    volumes:
      - "/:/host:ro,rslave"
    command:
      - '--path.rootfs=/host'

  prometheus:
    image: prom/prometheus
    container_name: prometheus
    restart: always
    network_mode: host
    pid: host
    volumes:
      - ./Prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
      - ./Prometheus/alert.rules.yml:/alertmanager/alert.rules.yml
    ports:
      - "9090:9090"

  grafana:
    image: grafana/grafana
    container_name: grafana
    restart: always
    network_mode: host
    pid: host
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=123
    volumes:
      - ./Grafana/datasource.yml:/etc/grafana/provisioning/datasources/datasource.yml
      - ./Grafana/providers.yml:/etc/grafana/provisioning/dashboards/providers.yml
    ports:
      - "3000:3000"

  alertmanager:
    image: prom/alertmanager
    container_name: manager
    restart: always
    network_mode: host
    pid: host
    volumes:
      - ./Alertmanager/alertmanager.yml:/etc/alertmanager/alertmanager.yml
    ports:
      - "9093:9093"

  cadvisor:
    image: gcr.io/cadvisor/cadvisor:v0.47.2
    container_name: cadvisor
    restart: always
    privileged: true
    network_mode: host
    pid: host
    devices:
      - /dev/kmsg
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:ro
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
      - /dev/disk/:/dev/disk:ro
    ports:
      - "8081:8080"

  blackbox_exporter:
    image: prom/blackbox-exporter
    container_name: blackbox_exporter
    restart: always
    network_mode: host
    pid: host
    ports:
      - "9115:9115"

