apiVersion: 1

providers:

- name: 'provider'

  orgId: 1

  folder: ''

  folderUid: ''

  type: file

  disableDeletion: false

  editable: true

  updateIntervalSeconds: 10
  options:
    path: /var/lib/grafana/dashboards


